// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeStructure.Infrastructure;

namespace TreeStructure.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211214202358_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeStructure.Domain.Models.NodeElement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NodeElementid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("NodeElementid");

                    b.ToTable("NodeElements");
                });

            modelBuilder.Entity("TreeStructure.Domain.Models.NodeElement", b =>
                {
                    b.HasOne("TreeStructure.Domain.Models.NodeElement", null)
                        .WithMany("nodeElements")
                        .HasForeignKey("NodeElementid");
                });

            modelBuilder.Entity("TreeStructure.Domain.Models.NodeElement", b =>
                {
                    b.Navigation("nodeElements");
                });
#pragma warning restore 612, 618
        }
    }
}
